carts/urls.py
from django.conf.urls import url

from .views import(
cart_home,
cart_update,
checkout_home,
checkout_done_view
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    ]

ecommerce/ecommerce/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
"""
from products.views import(
ProductListView,
product_list_view,
ProductDetailView,
ProductDetailSlugView,
product_detail_view,
ProductFeaturedListView,
ProductFeaturedDetailView
) """
from accounts.views import login_page,RegisterView,LoginView,guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

from .views import home_page,about_page,contact_page

urlpatterns = [
    url(r'^$', home_page,name='home'),
    url(r'^about/$', about_page, name ='about'),
    url(r'^contact/$', contact_page,name ='contact'),
    url(r'^register/$', RegisterView.as_view(),name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include('products.urls',namespace='products')),
    url(r'^search/', include('search.urls',namespace='search')),
    #url(r'^featured/$', ProductFeaturedListView.as_view()),
    #url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    #url(r'^products/$', ProductListView.as_view()),
    #url(r'^products-fbv/$', product_list_view),
    #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    #url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    #url(r'^products-fbv/(?P<pk>\d+)/$',product_detail_view),
    url(r'^login/$', LoginView.as_view(),name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view,name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view,name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view,name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^cart/', include('carts.urls',namespace='cart')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import(
ProductListView,
ProductDetailSlugView,
#product_list_view,
#ProductDetailView,

#product_detail_view,
#ProductFeaturedDetailView,
)

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^$', ProductListView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(),name='detail'),
    ]

templates/base/css.html
{%load static%}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{%static "css/bootstrap.min.css"%}">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- jquery-confirm CSS -->

templates/base/js.html
{%load static%}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/base/navbar.html
{%url 'home' as home_url%}
{%url 'contact' as contact_url%}
{%url 'products:list' as product_list_url%}
{%url 'login' as login_url%}
{%url 'logout' as logout_url%}
{%url 'register' as register_url%}
{%url 'cart:home' as cart_url%}

<nav class="navbar navbar-expand-lg nnavbar-dark bg-dark mb-5">
  <div class="container">
<!--  <a class="navbar-brand" href="#">{%if brand_name%}{{brand_name}}{%else%}ZS{%endif%}</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Featured</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'products:list'%}">Products</a>
      </li>
       {% if request.user.is_authenticated %}

      <li class="nav-item"{% if request.path == logout_url %}active{% endif %}>
        <a class="nav-link" href="{%url 'logout'%}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'register'%}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'login'%}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'contact'%}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{cart_url}}">{{request.session.cart_items}}<i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>
      </li>

    </ul>
        {%include 'search/snippets/search-form.html'%}
  </div>
</div>
</nav>